source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1" # installed by `gem jekyll`

gem "just-the-docs", "0.12.0" # pinned to the current release

gem "jekyll-jupyter-notebook"
# required by jekyll, no longer a default gem since Ruby 4.0
gem "logger"
